# This file is a template, and might need editing before it works on your project.
---
# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive


pages:
  script:
    - mkdir public
    - mkdir exampleSite/themes/
    - mkdir exampleSite/themes/sourgrough-starter/
    - cp -r layouts exampleSite/themes/sourgough-starter
    - cp -r static exampleSite/themes/sourgough-starter
    - cp -r archetypes exampleSite/themes/sourgough-starter
    - cp theme.toml exampleSite/themes/sourgough-starter
    - hugo -s exampleSite -d ../public
  artifacts:
    paths:
      - public
  only:
    - main
