
title = "Your Name"
baseURL = "https://sourgough.mrph.dev/"
languageCode = "en-us"
theme = "sourgough-starter"
relativeURLs = true

[markup.goldmark.renderer]
    unsafe= true

[params]
    backgroundPath = "images/SA_back.png"
    css= ["css/sourgough.css"]

[menu]
#----- Navbar links ------
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"

#----- NavBottom Links ------
  [[menu.bot]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/jack-alope/sourgough-hugo"
    pre = "fab fa-github"

  [[menu.bot]]
    identifier = "medium"
    name = "Medium"
    url = "/publications/"
    pre = "fab fa-medium-m"

  [[menu.bot]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "/projects/"
    pre = "fab fa-linkedin-in"

  [[menu.bot]]
    identifier = "googlescholar"
    name = "Google Scholar"
    url = "/projects/"
    pre = "fas fa-graduation-cap"

#-------- About section links ----- 
  [[menu.about]]
    identifier = "a"
    name = "Google Scholar"
    url = "/projects/"
    pre = "fas fa-graduation-cap"

  [[menu.about]]
    identifier = "b"
    name = "Google Scholar"
    url = "/projects/"
    pre = "fas fa-graduation-cap"

#----------- Text Links -------
  [[menu.link]]
    identifier = "email"
    name = "jack@mrph.dev"
    url = "/mailto"

  [[menu.link]]
    identifier = "resume"
    name = "resume"
    url = "/resume/"

[taxonomies]
  authors = "authors"



