
name: Update exampleSite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Remove and Clone Example Site
      run: |
        rm -rf exampleSite
        git clone https://gitlab.com/Jack-alope/sourgough-example.git exampleSite
    - name: Remove .git
      run: |
        rm -rf exampleSite/.git
        sed ‘s/sed/sourgough.mrph.dev/example.com/’ file.txt
        date >> exampleSite/README.md
    - name: Commit files
      run: |
        git config --local user.name "Github Action"
        git add .
        git commit -m "updated indexraw"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
